# Array
*an array is defined as a collection  of item that are sorted at contigious  memory
location.<br>
*it is a container which can hold a fixed number of items ,and these items should be the same type.<br>
*a combination of array a lot of time.the array  can reduce the overall size of the the code

In [5]:
import numpy as np

In [9]:
#1d_array
arr_1d=np.array([10,20,30])
print(arr_1d)
#2d_array
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("2d array:\n",arr_2d)

[10 20 30]
2d array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Array v/s List<br>
* a list cannot handle mathematical operation ,while array can .<br>
* an array  consume less memory than list<br>
* using array is faster than list<br>


# List V/S NumPy

In [11]:
#list multiplication operation
list_cost=[10,20,30,40]
print("list of sales: ",list_cost*2)
#array Multiplication Operation
arr_cost=np.array([10,20,30,40])
print("arr of sales:",arr_cost*2)

list of sales:  [10, 20, 30, 40, 10, 20, 30, 40]
arr of sales: [20 40 60 80]


In [13]:
import time as t
#list time
start=t.time()
list_num=[i*2 for i in range(1000000)]
print("List operation:",t.time()-start)
#Array Time
start=t.time()
arr_nums=np.arange(1000000)*2
print("Array operation:",t.time()-start)

List operation: 0.09389901161193848
Array operation: 0.0074920654296875


# Creating array from scratch

In [16]:
#zero array
zeros=np.zeros((3,2))
print("Zero array\n", zeros)
#one array
ones=np.ones((2,3))
print("Ones array\n", ones)
#full array
full=np.full((3,3),9)
print("Full array\n", full)
#random array
random=np.random.random((2,2))
print("Random array\n", random)
#Range arange(start,stop,step)
range=np.arange(10,21,1)
print("Range 10 to 20\n", range)

Zero array
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Ones array
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
Random array
 [[0.42654255 0.50443745]
 [0.80668368 0.64496159]]
Range 10 to 20
 [10 11 12 13 14 15 16 17 18 19 20]
