# Array
*an array is defined as a collection  of item that are sorted at contigious  memory
location.<br>
*it is a container which can hold a fixed number of items ,and these items should be the same type.<br>
*a combination of array a lot of time.the array  can reduce the overall size of the the code

In [2]:
import numpy as np

In [3]:
#1d_array
arr_1d=np.array([10,20,30])
print(arr_1d)
#2d_array
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("2d array:\n",arr_2d)

[10 20 30]
2d array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Array v/s List<br>
* a list cannot handle mathematical operation ,while array can .<br>
* an array  consume less memory than list<br>
* using array is faster than list<br>


# List V/S NumPy

In [4]:
#list multiplication operation
list_cost=[10,20,30,40]
print("list of sales: ",list_cost*2)
#array Multiplication Operation
arr_cost=np.array([10,20,30,40])
print("arr of sales:",arr_cost*2)

list of sales:  [10, 20, 30, 40, 10, 20, 30, 40]
arr of sales: [20 40 60 80]


In [5]:
import time as t
#list time
start=t.time()
list_num=[i*2 for i in range(1000000)]
print("List operation:",t.time()-start)
#Array Time
start=t.time()
arr_nums=np.arange(1000000)*2
print("Array operation:",t.time()-start)

List operation: 0.054447174072265625
Array operation: 0.003864765167236328


# Creating array from scratch

In [6]:
#zero array
zeros=np.zeros((3,2))
print("Zero array\n", zeros)
#one array
ones=np.ones((2,3))
print("Ones array\n", ones)
#full array
full=np.full((3,3),9)
print("Full array\n", full)
#random array
random=np.random.random((2,2))
print("Random array\n", random)
#Range arange(start,stop,step)
range=np.arange(10,21,1)
print("Range 10 to 20\n", range)

Zero array
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Ones array
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
Random array
 [[0.13884265 0.22423917]
 [0.13475799 0.6022536 ]]
Range 10 to 20
 [10 11 12 13 14 15 16 17 18 19 20]


Vector,Matrix & Tensor

In [7]:
vector=np.array([1,2,3,4,5,6,7,8])
print("vector:",vector)
matrix=np.array([[1,2,3],
                 [4,5,6]])
print("Matrix:\n",matrix)
tensor=np.array([[[10,20],[30,40],[50,60],[70,80]]])
print("Tensor:\n",tensor)

vector: [1 2 3 4 5 6 7 8]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[10 20]
  [30 40]
  [50 60]
  [70 80]]]


Array Properties

In [8]:
tensor=np.array([[[10,20,100],[30,40,200]],
                  [[50,60,300],[70,80,400]]])
print("Shape:",tensor.shape)
print("Dimension",np.ndim(tensor))
print("size",np.size(tensor))
print("DataType:",tensor.dtype)
print("Length:",len(tensor))
print("Convert to diff data type:\n",tensor.astype(str))

Shape: (2, 2, 3)
Dimension 3
size 12
DataType: int64
Length: 2
Convert to diff data type:
 [[['10' '20' '100']
  ['30' '40' '200']]

 [['50' '60' '300']
  ['70' '80' '400']]]


Array Reshaping

In [13]:
#one-D to two-D
arr=np.arange(12)
reshap=arr.reshape(6,2)
print("Reshape:\n",reshap)
#Two-D to one-D
matrix=np.array([[10,20,30],
                 [40,50,60]])
flat=matrix.flatten()
print("Flatten:",flat)

Reshape:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Flatten: [10 20 30 40 50 60]
