NumPy Array Operations

In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40,50,60,70])
print("Basic Slicing :",arr[:3])
print("Slicing with step:",arr[0:6:2])
print("-ve Indexing:",arr[-1])

Basic Slicing : [10 20 30]
Slicing with step: [10 30 50]
-ve Indexing: 70


In [3]:
#sales year wise id 2023,2024,2025
sales=np.array([[0,10000,15000,18000],#Chocolate
                [1,14000,26000,32000],#Pizza
                [2,31000,24000,35000] #Ice cream
                ])
print("pizza sale 2024:",sales[1,2])
print("Chocolate sales:",sales[0,1:])
print("sales of all item 2023:",sales[:,1])
print("Pizza sales date 2023,2024",sales[1,1:3])
print("Last two year for pizza,Ice cream:",sales[1:,2:],"\n")

pizza sale 2024: 26000
Chocolate sales: [10000 15000 18000]
sales of all item 2023: [10000 14000 31000]
Pizza sales date 2023,2024 [14000 26000]
Last two year for pizza,Ice cream: [[26000 32000]
 [24000 35000]] 



Sorting


In [4]:
arr=np.array([5,1,8,2,7,3,9,4])
print("sort array:",np.sort(arr))
matrix=np.array([[5,4,2],
                 [3,1,6],
                 [8,7,3]])
print("Sorting matrix col:\n",np.sort(matrix, axis=0))
print("Sorting matrix row:\n",np.sort(matrix, axis=1))

sort array: [1 2 3 4 5 7 8 9]
Sorting matrix col:
 [[3 1 2]
 [5 4 3]
 [8 7 6]]
Sorting matrix row:
 [[2 4 5]
 [1 3 6]
 [3 7 8]]


Filter and Mask

In [5]:
#Filter
nums=np.array([5,1,8,2,7,3,9,4])
even_nums=nums[nums%2==0]
print("even number:\n",even_nums,"\n")

#filter with mask

cgpa=np.array([9.9,9.8,7.8,6.7,7.7,6.5,6,5,4])
mask=cgpa>5
print("mask:",mask)

even number:
 [8 2 4] 

mask: [ True  True  True  True  True  True  True False False]


Join

In [6]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

combined=np.concatenate([arr1,arr2])
print("combined:",combined)

combined: [ 1  2  3  4 10 20 30 40]


In [7]:
matrix1=np.array([[10,20],
                 [30,40]])
matrix2=np.array([[100,200],
                  [300,400]])
print("vertical\n",np.vstack([matrix1,matrix2]))
print("horizontal\n",np.hstack([matrix1,matrix2]))

vertical
 [[ 10  20]
 [ 30  40]
 [100 200]
 [300 400]]
horizontal
 [[ 10  20 100 200]
 [ 30  40 300 400]]


Adding & Removing

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9])
#slice data
print("split:",np.split(arr,3))
#append
print("add:",np.append(arr,50))
#Insert
print("Insert:",np.insert(arr,0,9))
#remove
print("remove:",np.delete(arr,2))

split: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
add: [ 1  2  3  4  5  6  7  8  9 50]
Insert: [9 1 2 3 4 5 6 7 8 9]
remove: [1 2 4 5 6 7 8 9]


Mathematical operation

In [9]:
arr1=np.array([15,20,30,40,45])
arr2=np.array([2,3,4,5,6])

print("Addition:",np.add(arr1,arr2))
print("Substraction:",np.subtract(arr1,arr2))
print("Multiplication:",np.multiply(arr1,arr2))
print("Division:",np.divide(arr1,arr2))
print("Dot Product:",np.dot(arr1,arr2))

Addition: [17 23 34 45 51]
Substraction: [13 17 26 35 39]
Multiplication: [ 30  60 120 200 270]
Division: [7.5        6.66666667 7.5        8.         7.5       ]
Dot Product: 680


In [10]:
arr=np.array([15,20,30,40,45])
pw=np.array([3])
print("Power:",np.power(arr,pw))

Power: [ 3375  8000 27000 64000 91125]


In [11]:
arr=np.array([64,81,16,49,4])
print("SQRT",np.sqrt(arr))

SQRT [8. 9. 4. 7. 2.]


In [12]:
matrix=np.array([[1,2,3],
                [4,5,6]])
print("2D Array:\n",matrix,"\n")
print("Add Row:\n",np.insert(matrix, 1, [7,8,9], axis=0),"\n")
print("Add Column:\n",np.insert(matrix, 1, [7,8], axis=1),"\n")
print("Remove Row:\n",np.delete(matrix, 1, axis=0),"\n")
print("Remove Column:\n",np.delete(matrix, 1, axis=1),"\n")
#how to use fancy index and np.where in NumPy


2D Array:
 [[1 2 3]
 [4 5 6]] 

Add Row:
 [[1 2 3]
 [7 8 9]
 [4 5 6]] 

Add Column:
 [[1 7 2 3]
 [4 8 5 6]] 

Remove Row:
 [[1 2 3]] 

Remove Column:
 [[1 3]
 [4 6]] 



In [13]:
# Fancy indexing with a 1D array
scores = np.array([72, 91, 65, 88, 79])
selected = scores[[1, 3, 4]]
print("Scores at positions 1, 3, and 4:", selected)

# Fancy indexing with a 2D array: select rows and columns together
sales = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("Selected rows 0 and 2:\n", sales[[0, 2]])
print("Selected values at (row, column) pairs:", sales[[0, 2], [1, 0]])

# np.where(condition) returns the indices where the condition is True
even_positions = np.where(scores % 2 == 0)
print("Positions of even scores:", even_positions[0])
print("Even scores:", scores[even_positions])

# np.where(condition, value_if_true, value_if_false) replaces values by condition
result = np.where(scores >= 80, "Pass", "Needs improvement")
print("Result:", result)

Scores at positions 1, 3, and 4: [91 88 79]
Selected rows 0 and 2:
 [[10 20 30]
 [70 80 90]]
Selected values at (row, column) pairs: [20 70]
Positions of even scores: [0 3]
Even scores: [72 88]
Result: ['Needs improvement' 'Pass' 'Needs improvement' 'Pass' 'Needs improvement']
